version: "3.8"

services:
  localstack-baas:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-baas}"
    image: localstack/localstack
    ports:
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "4566:4566" # LocalStack Gateway
      - "4572:4572" # S3 Port
      - "4574:4574" # Lambda Port
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3,lambda
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  localstack-baas-init:
    image: amazon/aws-cli
    depends_on:
      - localstack-baas
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-central-1
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack-baas:4566 s3api create-bucket --bucket baas --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1
      "
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/