name: Run benchmark request on AWS

on:
  workflow_dispatch:
    inputs:
      benchmark_type:
        description: One of the supported benchmark type
        required: true
        type: choice
        options:
          - jmh
          - jmh-with-async
          - jmh-with-prof
          - jcstress
      benchmark_path:
        type: string
        required: true
        description: S3 url to benchmark jar
      s3_result_bucket:
        type: string
        default: baas-lynx-main
        description: S3 bucket name for benchmark results
      request_id:
        type: string
        description: ID of benchmark run request
      results_path:
        type: string
        description: S3 or local path to benchmark results
      parameters:
        type: string
        description: Additional parameters for benchmark
      worker_instance_family:
        description: One of the supported EC2 worker instance family
        default: c5
        type: choice
        options:
          - c5
          - c6i
          - c7i
      worker_instance_size:
        description: One of the supported EC2 worker instance size
        default: 2xlarge
        type: choice
        options:
          - 2xlarge
          - 4xlarge
          - 8xlarge
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AMI_NAME: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
jobs:
  start-runner:
    uses: ./.github/workflows/start-ec2-runner.yml
    permissions:
      id-token: write
      contents: read
    with:
      aws-region: ${{ vars.AWS_REGION }}
      subnet-id: ${{ vars.SUBNET_ID }}
      security-group-id: ${{ vars.SECURITY_GROUP_ID }}
      ec2-instance-type: ${{ inputs.worker_instance_family }}.${{ inputs.worker_instance_size }}
    secrets:
      workflow-role-arn: ${{ secrets.WORKFLOW_ROLE_ARN }}
      runner-role-name: ${{ secrets.RUNNER_ROLE_NAME }}
      gha-ec2-pat: ${{ secrets.GHA_EC2_PAT }}

  call-exec-benchmark-workflow:
    name: Run Benchmark runner workflow
    needs:
      - start-runner
    uses: ./.github/workflows/exec-single-benchmark.yml
    with:
      request-id: ${{ inputs.request_id }}
      benchmark-type:  ${{ inputs.benchmark_type }}
      benchmark-path: ${{ inputs.benchmark_path }}
      s3-result-bucket: ${{ inputs.s3_result_bucket }}
      results-path: ${{ inputs.results_path }}
      parameters: ${{ inputs.parameters }}
      gha-runner-type: ${{ needs.start-runner.outputs.label }}
      aws-region: ${{ vars.AWS_REGION }}
      async-profiler-version: ${{ vars.ASYNC_PROFILER_VERSION }}
    secrets:
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}

  stop-runner:
    uses: ./.github/workflows/stop-ec2-runner.yml
    permissions:
      id-token: write
      contents: read
    needs:
      - start-runner
      - call-exec-benchmark-workflow
    if: always()
    with:
      label: ${{ needs.start-runner.outputs.label }}
      ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      workflow-role-arn: ${{ secrets.WORKFLOW_ROLE_ARN }}
      gha-ec2-pat: ${{ secrets.GHA_EC2_PAT }}
