name: CI PR Maven Build

on:
  pull_request:   # Run workflow on PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and run tests (unit and integration)
        run: mvn -B clean verify
